const STORAGE_KEY='habit_tracker_v1';
const BACKUP_KEY='habit_tracker_v1_backup';
const defaultState={habits:[{id:'h1',name:'Lire',anchor:'☕ Après mon café',micro:'Lire 2 minutes',feel:'Je me sens plus calme',days:[1,1,0,1,2,0,0],done:false,stage:'🌿'},{id:'h2',name:'Respirer',anchor:'🪥 Après mes dents',micro:'3 respirations',feel:'Je me sens ancré·e',days:[1,1,1,1,1,2,0],done:true,stage:'🌱'},{id:'h3',name:'Marcher',anchor:'🍽️ Après le déjeuner',micro:'Marcher 2 minutes',feel:'Je me sens plus léger·ère',days:[1,0,1,0,1,2,0],done:false,stage:'🌳'}],step:1,max:3,selectedAnchor:'Après mon café',micro:'Lire 2 minutes',tone:'Doux',updatedAt:null};
const state=loadState(); const $=s=>document.querySelector(s);
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return structuredClone(defaultState);return migrateState(JSON.parse(raw));}catch{try{return migrateState(JSON.parse(localStorage.getItem(BACKUP_KEY)||'{}'));}catch{return structuredClone(defaultState)}}}
function migrateState(data){const base=structuredClone(defaultState);const merged={...base,...data};merged.habits=(data.habits||base.habits).slice(0,3).map((h,i)=>({id:h.id||`h${i+1}`,name:h.name||base.habits[i].name,anchor:h.anchor||'Après un moment naturel',micro:h.micro||'Juste commencer',feel:h.feel||'Je me sens mieux',days:Array.isArray(h.days)?h.days.slice(0,7):[0,0,0,0,0,0,0],done:!!h.done,stage:h.stage||'🌱'}));return merged;}
function persistState(){state.updatedAt=new Date().toISOString();const payload=JSON.stringify(state);localStorage.setItem(BACKUP_KEY,payload);localStorage.setItem(STORAGE_KEY,payload)}
function home(){const d=state.habits.filter(h=>h.done).length;$('#home').innerHTML=`<div class='header-line'><p class='muted'>${new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})}</p><span class='pill'>1% mieux chaque jour</span></div><h1>${d===state.max?'Bravo ! 🎉':'Bonjour 👋'}</h1><div class='ring' style='background:conic-gradient(#3d9e5f ${(d/state.max)*360}deg,#ececec 0)'><b>${d}/${state.max}</b></div><div class='card' style='background:#fff8ec;border-color:#f2dcb7'>🔥 5 jours — rater un jour ne retire pas tes progrès.</div><div class='section'>Aujourd'hui</div>${state.habits.map((h,i)=>`<article class='habit ${h.done?'done':''}'><div class='row'><div><div class='title'><span class='plant'>${h.stage}</span> ${h.name}</div><div class='muted'>${h.anchor}</div></div><button class='check' onclick='toggleHabit(${i})'>✓</button></div><div class='week'>${h.days.map(v=>`<span class='dot ${v===1?'ok':v===2?'grace':''}'></span>`).join('')}</div><p class='feel'>${h.feel}</p></article>`).join('')}<div class='card pill' style='margin-top:12px'>🛡️ 2 jours de rattrapage disponibles</div>`}
function add(){const p=[1,2,3,4].map(i=>`<span class='${i<=state.step?'on':''}'></span>`).join('');$('#add').innerHTML=`<h1>Ajouter une habitude</h1><div class='progress'>${p}</div><div class='flow ${state.step===1?'active':''}'><h2>Quelle habitude ?</h2><input value='Lire'/></div><div class='flow ${state.step===2?'active':''}'><h2>Quand est-ce que tu vas le faire ?</h2><div class='hint blue'>Les habitudes s'installent mieux après un moment naturel.</div>${['Après mon café','Après le déjeuner','Après la douche','Après mon réveil','Après le travail','Après le dîner'].map(a=>`<div class='anchor-option ${state.selectedAnchor===a?'active':''}' onclick="setAnchor('${a}')">${a}</div>`).join('')}</div><div class='flow ${state.step===3?'active':''}'><h2>Quelle version minuscule ?</h2><div class='hint green'>Ne jamais rater est plus important que faire beaucoup.</div><input value='${state.micro}' oninput='state.micro=this.value;persistState();render()'/></div><div class='flow ${state.step===4?'active':''}'><h2>Comment tu veux te sentir après ?</h2><div class='hint amber'>On change parce qu'on veut se sentir différemment.</div><div class='card'><b>Récap :</b> Après <i>${state.selectedAnchor}</i>, je fais <i>${state.micro}</i>.</div></div><div class='row' style='margin-top:12px'><button class='chip' onclick='prevStep()'>Retour</button><button class='chip' style='background:#1a1a1a;color:#fff' onclick='nextStep()'>Continuer</button></div>`}
function garden(){ $('#garden').innerHTML=`<div class='ghead'><h1>Mon Jardin</h1><p class='muted'>Total cumulé : 52 jours</p><div class='garden'><span class='plant'>🌱</span><span class='plant selected'>🌿</span><span class='plant'>🌳</span></div></div><div class='card'><h2>Détail 28 jours</h2><div class='heat'>${Array.from({length:28},(_,i)=>`<span class='cell ${i%5===0?'done':i%7===0?'grace':''}'></span>`).join('')}</div></div>`}
function reminders(){const msg=state.tone==='Doux'?'Petit pas maintenant ? 🌱':state.tone==='Neutre'?'Ton ancre est passée, on essaie ?':'Momentum 2 minutes !';$('#reminders').innerHTML=`<h1>Rappels bienveillants</h1><div class='card'><h2>Ton</h2><div class='chips'>${['Doux','Neutre','Motivant'].map(t=>`<button class='chip' onclick="setTone('${t}')" style='${state.tone===t?'border-color:#3d9e5f;background:#e8f7ee':''}'>${t}</button>`).join('')}</div></div><div class='card' style='margin-top:10px'>Exemple live : « ${msg} »</div>`}
function profile(){ $('#profile').innerHTML=`<h1>Profil</h1><div class='card'><h2>Stockage local (téléphone)</h2><p class='muted'>Toutes les données restent sur ce téléphone (localStorage).</p><p class='muted'>Dernière sauvegarde locale: ${state.updatedAt?new Date(state.updatedAt).toLocaleString('fr-FR'):'jamais'}</p><p class='muted'>Aucune synchronisation cloud active.</p></div></div>`}
function render(){home();add();garden();reminders();profile()}
window.toggleHabit=i=>{state.habits[i].done=!state.habits[i].done;persistState();render()};window.nextStep=()=>{state.step=Math.min(4,state.step+1);persistState();render()};window.prevStep=()=>{state.step=Math.max(1,state.step-1);persistState();render()};window.setAnchor=a=>{state.selectedAnchor=a;persistState();render()};window.setTone=t=>{state.tone=t;persistState();render()};window.persistState=persistState;
document.querySelectorAll('.footer-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(b.dataset.tab).classList.add('active');document.querySelectorAll('.footer-nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on')});
persistState();render();
const start=document.body.dataset.startTab;if(start){document.querySelector(`.footer-nav button[data-tab='${start}']`)?.click();}
